package:
  name: refugue
  version: 0.0.0a0.dev0

source:
  fn: refugue-0.0.0a0.dev0.tar.gz
  url: https://github.com/salotz/refugue/releases/download//{{ version }}/{{ name }}-{{ version }}.tar.gz
  # TODO: way to specify a hole or 
  sha256:

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - refugue = refugue.cli:cli

requirements:
  build:
    - python
    - setuptools
    - wheel

  host:
    - python
    
  run:
    - python
    

about:
  home: https://github.com/salotz/refugue
  license: MIT
  license_file: LICENSE
  summary: "Manage data working sets between computers and drives"
  doc_url: https://salotz.github.io/refugue
  dev_url: https://github.com/salotz/refugue

extra:
  recipe-maintainers:
    - salotz
